aalib
appstream
brltty
capstone
c-ares
cdparanoia
dbus-glib
dtc
edk2-aarch64
edk2-arm
edk2-ovmf
entr
freeglut
glu
glusterfs
gst-plugins-base
gst-plugins-good
gtk2
gtk-vnc
ifuse
iniparser
iproute2
kitty
kitty-shell-integration
kitty-terminfo
libadwaita
libburn
libcaca
libcacard
libheif
libiscsi
libisoburn
libisofs
liblouis
libluv
libnbd
libngtcp2
libosinfo
librsync
libshout
libslirp
libspeechd
libtraceevent
libtracefs
libutf8proc
libvirt
libvirt-glib
libvirt-python
libvterm
libxdp
libxmlb
lua51-lpeg
msgpack-c
multipath-tools
ndctl
neovim
nodejs
numactl
osinfo-db
otf-aurulent-nerd
otf-codenewroman-nerd
otf-comicshanns-nerd
otf-commit-mono-nerd
otf-droid-nerd
otf-firamono-nerd
otf-geist-mono-nerd
otf-hasklig-nerd
otf-hermit-nerd
otf-monaspace-nerd
otf-opendyslexic-nerd
otf-overpass-nerd
phodav
power-profiles-daemon
pyenv
python-charset-normalizer
python-idna
python-requests
python-urllib3
qemu-audio-alsa
qemu-audio-dbus
qemu-audio-jack
qemu-audio-oss
qemu-audio-pa
qemu-audio-pipewire
qemu-audio-sdl
qemu-audio-spice
qemu-base
qemu-block-curl
qemu-block-dmg
qemu-block-gluster
qemu-block-iscsi
qemu-block-nfs
qemu-block-ssh
qemu-chardev-baum
qemu-chardev-spice
qemu-common
qemu-desktop
qemu-docs
qemu-emulators-full
qemu-full
qemu-hw-display-qxl
qemu-hw-display-virtio-gpu
qemu-hw-display-virtio-gpu-gl
qemu-hw-display-virtio-gpu-pci
qemu-hw-display-virtio-gpu-pci-gl
qemu-hw-display-virtio-vga
qemu-hw-display-virtio-vga-gl
qemu-hw-s390x-virtio-gpu-ccw
qemu-hw-usb-host
qemu-hw-usb-redirect
qemu-hw-usb-smartcard
qemu-img
qemu-pr-helper
qemu-system-aarch64
qemu-system-alpha
qemu-system-alpha-firmware
qemu-system-arm
qemu-system-arm-firmware
qemu-system-avr
qemu-system-cris
qemu-system-hppa
qemu-system-hppa-firmware
qemu-system-loongarch64
qemu-system-m68k
qemu-system-microblaze
qemu-system-microblaze-firmware
qemu-system-mips
qemu-system-or1k
qemu-system-ppc
qemu-system-ppc-firmware
qemu-system-riscv
qemu-system-riscv-firmware
qemu-system-rx
qemu-system-s390x
qemu-system-s390x-firmware
qemu-system-sh4
qemu-system-sparc
qemu-system-sparc-firmware
qemu-system-tricore
qemu-system-x86
qemu-system-x86-firmware
qemu-system-xtensa
qemu-tests
qemu-tools
qemu-ui-curses
qemu-ui-dbus
qemu-ui-egl-headless
qemu-ui-gtk
qemu-ui-opengl
qemu-ui-sdl
qemu-ui-spice-app
qemu-ui-spice-core
qemu-user
qemu-vhost-user-gpu
qemu-vmsr-helper
rustup
sdl2_image
seabios
spice
spice-gtk
spice-protocol
taglib
tmux
traceroute
tree-sitter
tree-sitter-c
tree-sitter-cli
tree-sitter-lua
tree-sitter-markdown
tree-sitter-query
tree-sitter-vim
tree-sitter-vimdoc
ttc-iosevka-slab
ttf-0xproto-nerd
ttf-3270-nerd
ttf-agave-nerd
ttf-anonymouspro-nerd
ttf-arimo-nerd
ttf-bigblueterminal-nerd
ttf-bitstream-vera-mono-nerd
ttf-cascadia-code-nerd
ttf-cascadia-mono-nerd
ttf-cousine-nerd
ttf-d2coding-nerd
ttf-daddytime-mono-nerd
ttf-dejavu-nerd
ttf-envycoder-nerd
ttf-fantasque-nerd
ttf-firacode-nerd
ttf-gohu-nerd
ttf-go-nerd
ttf-hack-nerd
ttf-heavydata-nerd
ttf-iawriter-nerd
ttf-ibmplex-mono-nerd
ttf-inconsolata-go-nerd
ttf-inconsolata-lgc-nerd
ttf-inconsolata-nerd
ttf-intone-nerd
ttf-iosevka-nerd
ttf-iosevkaterm-nerd
ttf-iosevkatermslab-nerd
ttf-jetbrains-mono-nerd
ttf-lekton-nerd
ttf-liberation-mono-nerd
ttf-lilex-nerd
ttf-martian-mono-nerd
ttf-meslo-nerd
ttf-monofur-nerd
ttf-monoid-nerd
ttf-mononoki-nerd
ttf-mplus-nerd
ttf-nerd-fonts-symbols
ttf-nerd-fonts-symbols-common
ttf-nerd-fonts-symbols-mono
ttf-noto-nerd
ttf-profont-nerd
ttf-proggyclean-nerd
ttf-recursive-nerd
ttf-roboto-mono-nerd
ttf-sharetech-mono-nerd
ttf-sourcecodepro-nerd
ttf-space-mono-nerd
ttf-terminus-nerd
ttf-tinos-nerd
ttf-ubuntu-mono-nerd
ttf-ubuntu-nerd
ttf-victor-mono-nerd
ttf-zed-mono-nerd
twolame
unibilium
usbredir
vde2
vim
vim-runtime
virglrenderer
virt-install
virtiofsd
virt-manager
wavpack
wolfssl
xsel
zenity
zsh
